#!/usr/bin/env python3.1
# encoding: utf-8

"""
Example post-receive hook
Before use, set PAGE_REPO and PASTASPYGE variables
"""

# Local clone of this repository.
PAGE_REPO = "/path/to/local/clone/of/site/repository"
DOCUMENT_ROOT = "/document-root/for/site/"

# Path to pastaspyge source
PASTASPYGE = "/home/users/annttu/pastaspyge/"

# Virtualenv to user
VIRTUAL_ENV = ""

import sys
sys.path.insert(0, PASTASPYGE)

if VIRTUAL_ENV:
    from pastaspyge.utils import activate_env
    activate_env(VIRTUAL_ENV)

from pastaspyge.git_hooks import post_receive

post_receive(repo_dir=PAGE_REPO, document_root=DOCUMENT_ROOT)
